// Generated by zkube-codegen from zkube-core. Do not edit.
export const PROTOCOL_ACCOUNT_VERSION = 2 as const;
export const ARCADE_ACCOUNT_VERSION = 4 as const;
export const RULES_ACCOUNT_VERSION = 1 as const;
export const PLAYER_LABEL_ACCOUNT_VERSION = 1 as const;
export const ARENA_ENTRY_LAMPORTS = 20000000n;
export const ENTRY_DAILY_LAMPORTS = 12000000n;
export const ENTRY_WEEKLY_LAMPORTS = 4000000n;
export const ENTRY_SEASON_LAMPORTS = 2000000n;
export const ENTRY_OPERATOR_LAMPORTS = 2000000n;
export const SOL_PAYOUT_UNIT_LAMPORTS = 1000000n;
export const SECONDS_PER_DAY = 86400 as const;
export const WEEK_DAYS = 7 as const;
export const SEASON_DAYS = 28 as const;
export const MONDAY_EPOCH_DAY_ID = 4 as const;
export const DAILY_PRIZE_WEIGHTS = [45, 25, 15, 10, 5] as const;
export const WEEKLY_PRIZE_WEIGHTS = [60, 25, 15] as const;
