// Generated by zkube-codegen from zkube-core. Do not edit.
export const PROTOCOL_ACCOUNT_VERSION = 2 as const;
export const ARCADE_ACCOUNT_VERSION = 3 as const;
export const RULES_ACCOUNT_VERSION = 1 as const;
export const PLAYER_LABEL_ACCOUNT_VERSION = 1 as const;
