import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { shareCardText } from "@/ui/components/profile/shareCardText";

// French and its neighboring store locales, plus unchanged whitespace/Indian
// grouping controls. This is a tested compatibility scope, not a locale catalog.
export const SHARE_LOCALES = ["fr", "fr-FR", "fr-CA", "fr-BE", "fr-CH", "fr-LU", "fr-MC", "en-US", "en-CA", "de-DE", "de-CH", "nl-BE", "it-IT", "es-ES", "pt-PT", "ru-RU", "sv-SE", "pl-PL", "hi-IN"] as const;

export function numberPolicy(locale: string) {
  const formatter = new Intl.NumberFormat(locale);
  const parts = formatter.formatToParts(1234567890123);
  const separators = [...new Set(parts.filter(p => p.type === "group").map(p => p.value))];
  const integers = parts.filter(p => p.type === "integer").map(p => p.value);
  if (separators.length !== 1 || integers.some(p => !/^[0-9]+$/.test(p))) throw new Error(`Unsupported share number parts: ${locale}`);
  const sizes = integers.slice(1).reverse().map(p => p.length);
  if (sizes.length < 2 || sizes.slice(1).some(size => size !== sizes[1])) throw new Error(`Nonuniform share grouping: ${locale}`);
  const groupSizes = sizes[0] === sizes[1] ? [sizes[0]] : [sizes[0], sizes[1]];
  let minimumGroupedValue = 1;
  while (!formatter.formatToParts(minimumGroupedValue).some(p => p.type === "group")) {
    minimumGroupedValue *= 10;
    if (!Number.isSafeInteger(minimumGroupedValue)) throw new Error(`No bounded grouping threshold: ${locale}`);
  }
  return { locale, separator: separators[0], groupSizes, minimumGroupedValue };
}

export function shareFixtures() {
  const original = [
    { name: "Alice", guardian: "Mako", realm: "Tiki", objective: "Combo 2+", total: "12345", score: 1234567, streak: 9, locale: "en-US" },
    { name: "Élodie", guardian: "Balam", realm: "Mayan", objective: "Classic Score", total: "0", score: 10000, streak: 1, locale: "fr-FR" },
    { name: "Player", guardian: "Amaru", realm: "Inca", objective: "Bonus Breaks", total: "18446744073709551615", score: 0, streak: 0, locale: "en-US" },
  ];
  const cases = [...original, ...SHARE_LOCALES.flatMap(locale => [0, 999, 1000, 9999, 10000, 1234567].map(score => ({
    name: "Élodie", guardian: "Balam", realm: "Mayan", objective: "Classic Score", total: "0", score, streak: 1, locale,
  })))].map(row => ({ ...row, expected: shareCardText({ displayName: row.name, guardianName: row.guardian,
    realm: row.realm, objective: row.objective, objectiveTotal: BigInt(row.total), dailyScore: row.score, streak: row.streak }, row.locale) }));
  const policies = SHARE_LOCALES.map(numberPolicy);
  const entries = policies.map(p => `            { ${JSON.stringify(p.locale)}, new Policy(${JSON.stringify(p.separator)}, new[] { ${p.groupSizes.join(", ")} }, ${p.minimumGroupedValue}UL) },`).join("\n");
  const code = `// Generated by client/tools/unity/share-fixtures.ts from Intl.formatToParts; do not edit.
using System;
using System.Collections.Generic;
namespace ZKube.Local.App
{
    internal static class ShareNumberFormats
    {
        internal sealed class Policy
        {
            internal readonly string Separator;
            internal readonly int[] GroupSizes;
            internal readonly ulong MinimumGroupedValue;
            internal Policy(string separator, int[] sizes, ulong minimum)
            { Separator = separator; GroupSizes = sizes; MinimumGroupedValue = minimum; }
        }
        private static readonly Dictionary<string, Policy> Policies = new Dictionary<string, Policy>(StringComparer.OrdinalIgnoreCase)
        {
${entries}
        };
        internal static bool TryGet(string locale, out Policy policy) => Policies.TryGetValue(locale, out policy);
    }
}
`;
  return { cases, code };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url))
  process.stdout.write(JSON.stringify(shareFixtures(), null, 2) + "\n");
