interface KreditCoinProps {
  size?: number;
  className?: string;
  title?: string;
}

/**
 * The Kredit — the gold block token.
 *
 * Deliberately not the SOL coin. A Kredit is a prepaid entry, one-way and
 * never convertible back, so it must never look like the currency it was
 * bought with: `Coin` carries the Solana logomark and belongs beside a SOL
 * price, this belongs beside a Kredit count.
 *
 * Its face is the game's own block, not a guardian: a realm's mask would make
 * the shared currency belong to one of ten realms. Generated by
 * `client/tools/sprites/generate-kredit-coin.mjs` against the app icon, and
 * kept low-detail on purpose — it is drawn as small as fifteen pixels here.
 */
const KreditCoin: React.FC<KreditCoinProps> = ({
  size = 24,
  className = "",
  title,
}) => (
  <img
    src="/assets/common/kredit.png"
    alt={title ?? ""}
    aria-hidden={title ? undefined : true}
    draggable={false}
    width={size}
    height={size}
    className={`flex-none select-none ${className}`}
    style={{
      width: size,
      height: size,
      filter: `drop-shadow(0 ${Math.max(1, size * 0.04)}px ${size * 0.08}px rgba(0,0,0,0.55))`,
    }}
  />
);

export default KreditCoin;
