use super::CampaignCatalog;
use std::fmt::Write as _;
use zkube_core_wasm::native::{self, Field, FieldType};

pub fn outputs(catalog: &CampaignCatalog) -> Result<Vec<(&'static str, String)>, String> {
    Ok(vec![
        (
            "unity/Assets/ZKube/Generated/ClientPolicy.g.cs",
            format!(
                "// Generated from the program account bound; do not edit.\nnamespace ZKube.Core.Generated\n{{\n    public static partial class ClientPolicy\n    {{\n        public const uint ArenaBoardCapacity = {}U;\n    }}\n}}\n",
                zkube_program::state::ARENA_BOARD_CAPACITY,
            ),
        ),
        ("unity/Assets/ZKube/Generated/NativeSchema.g.cs", schema()),
        (
            "unity/Assets/ZKube/Generated/Protocol.g.cs",
            protocol(catalog),
        ),
        (
            "fixtures/native-run-trajectories.json",
            super::native_fixtures::render(catalog)?,
        ),
    ])
}

fn cs_type(kind: FieldType) -> &'static str {
    match kind {
        FieldType::U8 => "byte",
        FieldType::U16 => "ushort",
        FieldType::U32 => "uint",
        FieldType::U64 => "ulong",
        FieldType::Bytes(_) => "byte[]",
    }
}

fn read_expression(field: &Field, offset: usize) -> String {
    match field.kind {
        FieldType::U8 => format!("bytes[{offset}]"),
        FieldType::Bytes(n) => format!("NativeWire.Bytes(bytes, {offset}, {n})"),
        other => format!(
            "({})NativeWire.Read(bytes, {offset}, {})",
            cs_type(other),
            other.byte_len()
        ),
    }
}

fn emit_class(output: &mut String, name: &str, fields: &[Field], request_id: Option<u32>) {
    writeln!(output, "    public sealed class {name}\n    {{").unwrap();
    let header = usize::from(request_id.is_some()) * 2;
    writeln!(
        output,
        "        public const int ByteLength = {};",
        header + native::fields_len(fields)
    )
    .unwrap();
    if let Some(id) = request_id {
        writeln!(output, "        public const uint Operation = {id};").unwrap();
    }
    for field in fields {
        let initial = match field.kind {
            FieldType::Bytes(n) => format!(" = new byte[{n}];"),
            _ => String::new(),
        };
        writeln!(
            output,
            "        public {} {} {{ get; set; }}{initial}",
            cs_type(field.kind),
            field.name
        )
        .unwrap();
    }
    if request_id.is_some() {
        output.push_str("        public byte[] Encode()\n        {\n            var bytes = new byte[ByteLength];\n            NativeWire.Write(bytes, 0, 2, NativeSchema.AbiVersion);\n");
        for field in fields {
            let offset = header + native::field_range(fields, field.name).start;
            match field.kind {
                FieldType::Bytes(n) => writeln!(
                    output,
                    "            NativeWire.Copy({}, bytes, {offset}, {n});",
                    field.name
                )
                .unwrap(),
                other => writeln!(
                    output,
                    "            NativeWire.Write(bytes, {offset}, {}, {});",
                    other.byte_len(),
                    field.name
                )
                .unwrap(),
            }
        }
        output.push_str("            return bytes;\n        }\n");
    }
    // Tests decode fixture input requests; opaque core config/state tokens
    // continue to be decoded exclusively by the native engine.
    if request_id.is_none() || matches!(request_id, Some(1 | 4..=8)) {
        writeln!(output, "        public static {name} Decode(byte[] bytes)\n        {{\n            if (bytes == null || bytes.Length != ByteLength) throw new ArgumentException(\"Invalid {name} byte length\");").unwrap();
        if request_id.is_some() {
            output.push_str("            if (NativeWire.Read(bytes, 0, 2) != NativeSchema.AbiVersion) throw new ArgumentException(\"Unsupported request version\");\n");
        }
        writeln!(output, "            return new {name}\n            {{").unwrap();
        for field in fields {
            writeln!(
                output,
                "                {} = {},",
                field.name,
                read_expression(
                    field,
                    header + native::field_range(fields, field.name).start
                )
            )
            .unwrap();
        }
        output.push_str("            };\n        }\n");
    }
    output.push_str("    }\n\n");
}

fn schema() -> String {
    let mut output = String::from(
        "// Generated by zkube-codegen from the safe native schema. Do not edit.\nusing System;\n\nnamespace ZKube.Core.Generated\n{\n",
    );
    writeln!(output, "    public static class NativeSchema\n    {{\n        public const ushort AbiVersion = {};\n        public const ushort TraceVersion = {};\n        public const int RunConfigLength = {};\n        public const int RunStateLength = {};\n        public const int ResponseCapacity = {};\n    }}", native::ABI_VERSION, native::TRACE_VERSION, zkube_core_wasm::RUN_CONFIG_LEN, zkube_core_wasm::RUN_STATE_LEN, native::RESPONSE_CAPACITY).unwrap();
    output.push_str("    public enum CorePhase : byte\n    {\n");
    for (tag, name) in native::PHASE_TAGS {
        writeln!(output, "        {name} = {tag},").unwrap();
    }
    output.push_str("    }\n");
    output.push_str("    public enum NativeStatus : int\n    {\n");
    for (id, name) in native::STATUSES {
        writeln!(output, "        {name} = {id},").unwrap();
    }
    output.push_str("    }\n    public enum PresentationKind : byte\n    {\n");
    for (id, name, _) in native::TRACE_EVENTS {
        writeln!(output, "        {name} = {id},").unwrap();
    }
    output.push_str("    }\n    public static class PresentationSchema\n    {\n        public static int PayloadLength(PresentationKind kind)\n        {\n            switch (kind)\n            {\n");
    for (_, name, len) in native::TRACE_EVENTS {
        writeln!(
            output,
            "                case PresentationKind.{name}: return {len};"
        )
        .unwrap();
    }
    output.push_str("                default: throw new ArgumentException(\"Unknown presentation event\");\n            }\n        }\n    }\n\n");
    for op in native::OPERATIONS {
        if matches!(op.id, 10 | 11 | 20) {
            continue;
        }
        emit_class(
            &mut output,
            &format!("{}Request", op.name),
            op.fields,
            Some(op.id),
        );
    }
    emit_class(&mut output, "RunSummary", native::SUMMARY_FIELDS, None);
    emit_class(&mut output, "DailyPair", native::DAILY_PAIR_FIELDS, None);
    emit_class(
        &mut output,
        "CampaignProgressSummary",
        native::CAMPAIGN_PROGRESS_FIELDS,
        None,
    );
    output.push_str(r#"    public static class NativeWire
    {
        public static ulong Read(byte[] bytes, int offset, int count)
        {
            if (bytes == null || count < 1 || count > 8 || offset < 0 || offset > bytes.Length - count)
                throw new ArgumentException("Invalid integer range");
            ulong value = 0;
            for (int i = 0; i < count; i++) value |= (ulong)bytes[offset + i] << (8 * i);
            return value;
        }
        public static void Write(byte[] bytes, int offset, int count, ulong value)
        {
            if (bytes == null || count < 1 || count > 8 || offset < 0 || offset > bytes.Length - count)
                throw new ArgumentException("Invalid integer range");
            if (count < 8 && value >> (count * 8) != 0) throw new ArgumentException("Integer overflow");
            for (int i = 0; i < count; i++) bytes[offset + i] = (byte)(value >> (8 * i));
        }
        public static byte[] Bytes(byte[] bytes, int offset, int count)
        {
            if (bytes == null || offset < 0 || count < 0 || offset > bytes.Length - count)
                throw new ArgumentException("Invalid byte range");
            var value = new byte[count];
            Buffer.BlockCopy(bytes, offset, value, 0, count);
            return value;
        }
        public static void Copy(byte[] source, byte[] target, int offset, int count)
        {
            if (source == null || source.Length != count) throw new ArgumentException("Invalid fixed byte length");
            Buffer.BlockCopy(source, 0, target, offset, count);
        }
    }
}
"#);
    output
}

#[allow(clippy::too_many_lines)] // One emitted declaration mirrors the protocol/catalog source.
fn protocol(catalog: &CampaignCatalog) -> String {
    use zkube_core::{
        ARCADE_ACCOUNT_VERSION, ARENA_ENTRY_LAMPORTS, CAMPAIGN_TARGET_LADDER, CORE_VERSION,
        DAILY_MAX_MOVES, DAILY_PAIR_COUNT, DAILY_PAIR_SELECTION_SEED,
        DAILY_REWARD_CLAIM_WINDOW_SECONDS, DAILY_THEMES, ENTRY_DAILY_LAMPORTS,
        ENTRY_OPERATOR_LAMPORTS, LADDER_QUALIFY_POINTS, PLAYER_LABEL_ACCOUNT_VERSION,
        PLAYER_STATE_ACCOUNT_VERSION, PRESSURE_STEP, PROTOCOL_ACCOUNT_VERSION,
        SOL_PAYOUT_UNIT_LAMPORTS,
    };
    let mut output = String::from(
        "// Generated by zkube-codegen from zkube-core and campaign-v2.json. Do not edit.\nnamespace ZKube.Core.Generated\n{\n    public static class Protocol\n    {\n",
    );
    for (name, value) in [
        ("EntryLamports", ARENA_ENTRY_LAMPORTS),
        ("EntryDailyLamports", ENTRY_DAILY_LAMPORTS),
        ("EntryOperatorLamports", ENTRY_OPERATOR_LAMPORTS),
        ("PayoutUnitLamports", SOL_PAYOUT_UNIT_LAMPORTS),
        (
            "ClaimWindowSeconds",
            DAILY_REWARD_CLAIM_WINDOW_SECONDS as u64,
        ),
    ] {
        writeln!(output, "        public const ulong {name} = {value}UL;").unwrap();
    }
    for (name, value) in [
        ("DailyMaxMoves", u32::from(DAILY_MAX_MOVES)),
        ("PressureStep", PRESSURE_STEP),
        (
            "DailyPairCount",
            u32::try_from(DAILY_PAIR_COUNT).expect("pair count fits u32"),
        ),
        ("LadderQualifyPoints", LADDER_QUALIFY_POINTS),
        (
            "ProtocolAccountVersion",
            u32::from(PROTOCOL_ACCOUNT_VERSION),
        ),
        (
            "PlayerStateAccountVersion",
            u32::from(PLAYER_STATE_ACCOUNT_VERSION),
        ),
        ("ArcadeAccountVersion", u32::from(ARCADE_ACCOUNT_VERSION)),
        (
            "PlayerLabelAccountVersion",
            u32::from(PLAYER_LABEL_ACCOUNT_VERSION),
        ),
        ("CatalogVersion", zkube_core::CATALOG_VERSION),
    ] {
        writeln!(output, "        public const uint {name} = {value}U;").unwrap();
    }
    writeln!(
        output,
        "        public const string CoreVersion = \"{CORE_VERSION}\";"
    )
    .unwrap();
    let numbers = |values: &[u16]| {
        values
            .iter()
            .map(u16::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    };
    writeln!(
        output,
        "        public static readonly ushort[] CampaignTargets = {{ {} }};",
        numbers(&CAMPAIGN_TARGET_LADDER)
    )
    .unwrap();
    output.push_str("        public static readonly ushort[][] TierBlockWeights =\n        {\n");
    for row in &catalog.difficulty_weights {
        writeln!(output, "            new ushort[] {{ {} }},", numbers(row)).unwrap();
    }
    output
        .push_str("        };\n        public static readonly byte[][] DailyThemes =\n        {\n");
    for theme in DAILY_THEMES {
        writeln!(
            output,
            "            new byte[] {{ {}, {} }},",
            theme.kind.tag(),
            theme.value
        )
        .unwrap();
    }
    output.push_str("        };\n");
    writeln!(
        output,
        "        public static readonly byte[] DailySelectionSeed = {{ {} }};",
        DAILY_PAIR_SELECTION_SEED
            .iter()
            .map(u8::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();
    output.push_str("        public static readonly RealmDefinition[] Realms =\n        {\n");
    for map in &catalog.maps {
        writeln!(output, "            new RealmDefinition({}, new ushort[] {{ {} }}, new LevelDefinition[]\n            {{", map.map_id, numbers(&map.rules)).unwrap();
        for level in &map.levels {
            let bytes = |v: &[u8]| v.iter().map(u8::to_string).collect::<Vec<_>>().join(", ");
            writeln!(output, "                new LevelDefinition({}, new byte[] {{ {} }}, new byte[] {{ {} }}),", level.0, bytes(&level.1), bytes(&level.2)).unwrap();
        }
        output.push_str("            }),\n");
    }
    output.push_str("        };\n    }\n    public sealed class RealmDefinition\n    {\n        public readonly byte MapId;\n        public readonly ushort[] GuardianAndHeight;\n        public readonly LevelDefinition[] Levels;\n        public RealmDefinition(byte id, ushort[] rules, LevelDefinition[] levels) { MapId = id; GuardianAndHeight = rules; Levels = levels; }\n    }\n    public sealed class LevelDefinition\n    {\n        public readonly byte Tier;\n        public readonly byte[] Primary;\n        public readonly byte[] Secondary;\n        public LevelDefinition(byte tier, byte[] primary, byte[] secondary) { Tier = tier; Primary = primary; Secondary = secondary; }\n    }\n}\n");
    output
}
