// Generated by zkube-codegen from fixtures/campaign-catalog.json. Do not edit.

pub const REALM_RULES: [RealmRules; CAMPAIGN_MAP_COUNT] = [
    RealmRules {
        guardian: Guardian {
            bonus: Bonus::Wave,
            trigger: 1,
            threshold: 2,
        },
        starting_height: 4,
    },
    RealmRules {
        guardian: Guardian {
            bonus: Bonus::Hammer,
            trigger: 4,
            threshold: 2,
        },
        starting_height: 6,
    },
    RealmRules {
        guardian: Guardian {
            bonus: Bonus::Totem,
            trigger: 8,
            threshold: 10,
        },
        starting_height: 4,
    },
    RealmRules {
        guardian: Guardian {
            bonus: Bonus::Hammer,
            trigger: 9,
            threshold: 3,
        },
        starting_height: 6,
    },
    RealmRules {
        guardian: Guardian {
            bonus: Bonus::Wave,
            trigger: 2,
            threshold: 7,
        },
        starting_height: 5,
    },
    RealmRules {
        guardian: Guardian {
            bonus: Bonus::Totem,
            trigger: 6,
            threshold: 0,
        },
        starting_height: 4,
    },
    RealmRules {
        guardian: Guardian {
            bonus: Bonus::Hammer,
            trigger: 4,
            threshold: 3,
        },
        starting_height: 4,
    },
    RealmRules {
        guardian: Guardian {
            bonus: Bonus::Totem,
            trigger: 1,
            threshold: 3,
        },
        starting_height: 6,
    },
    RealmRules {
        guardian: Guardian {
            bonus: Bonus::Totem,
            trigger: 7,
            threshold: 2,
        },
        starting_height: 4,
    },
    RealmRules {
        guardian: Guardian {
            bonus: Bonus::Hammer,
            trigger: 4,
            threshold: 4,
        },
        starting_height: 4,
    },
];
