// Generated by `anchor build`; never hand-maintain instruction/account layouts.
// Keeping the import pointed at the build artifact makes ABI drift a TypeScript
// build failure instead of silently shipping a stale handwritten IDL.
import generatedIdl from "./generated/solana.json";
import type { Solana } from "./generated/solana";

export const IDL = generatedIdl as Solana;
export type ZkubeProgram = Solana;
