[toolchain]
anchor_version = "0.32.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana = "8vB8kAAsuxLGejEweuJRdnAAe5wuUFTdt2fRQjeqvC6v"

[programs.devnet]
solana = "8vB8kAAsuxLGejEweuJRdnAAe5wuUFTdt2fRQjeqvC6v"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
