#!/usr/bin/env python3
"""Reproduce local Unity art from the authored asset sources and pinned fonts.

--plan reads sources only. --sync writes generated Assets (run with Editor stopped).
--check compares generated bytes/catalog and stable GUIDs without touching Assets.
Then root runs ZKube.Editor.ZKubeAssetImports.Prepare in its serialized Editor window.
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import uuid
from editor_lease import editor_lease

PROJECT = Path(__file__).resolve().parents[1]
ROOT = PROJECT.parent
SOURCE = ROOT / "assets"
FONTS = PROJECT / "tools/font_sources"
ART = PROJECT / "Assets/ZKube/Art"
GENERATED = ART / "Generated"
RESOURCE = "Resources/ZKube"
GUID_NAMESPACE = uuid.UUID("d72898c9-d549-58e7-aace-58e1d6058843")


def digest(data):
    return hashlib.sha256(data).hexdigest()


def guid(path):
    return uuid.uuid5(GUID_NAMESPACE, path.relative_to(PROJECT).as_posix()).hex


def encoded(value):
    return (json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode()


def theme_catalog():
    return json.loads((SOURCE / "theme-catalog.generated.json").read_text())


def plan():
    catalog = theme_catalog()
    files = {}
    entries = []
    scopes = ["common"] + [theme["id"] for theme in catalog["themes"]]
    for scope in scopes:
        for source in sorted((SOURCE / scope).rglob("*")):
            if source.suffix.lower() not in {".png", ".mp3"}:
                continue
            if source.is_symlink() or not source.is_file():
                raise RuntimeError(f"Expected regular source asset: {source}")
            local = source.relative_to(SOURCE / scope)
            name = "__".join(local.with_suffix("").parts)
            data = source.read_bytes()
            entry = {"source": source.relative_to(ROOT).as_posix(), "sha256": digest(data),
                     "bytes": len(data), "scope": scope, "name": name}
            if source.suffix == ".png":
                if data[:8] != b"\x89PNG\r\n\x1a\n":
                    raise RuntimeError(f"Not a PNG: {source}")
                width, height = struct.unpack(">II", data[16:24])
                destination = GENERATED / "Sprites" / scope / f"{name}.png"
                entry.update(kind="sprite", width=width, height=height,
                             atlas=f"ZKube/Atlases/{scope}", sprite=name)
            else:
                destination = GENERATED / RESOURCE / "Audio" / scope / f"{name}.mp3"
                entry.update(kind="audio", resource=f"ZKube/Audio/{scope}/{name}",
                             streaming="/musics/" in source.as_posix())
            if destination in files:
                raise RuntimeError(f"Flattened import path collision: {destination}")
            entry.update(asset=destination.relative_to(PROJECT).as_posix(), guid=guid(destination))
            entries.append(entry)
            files[destination] = data
    # Keep the ordinary source lookup before adding byte-identical portrait
    # imports; those copies must not replace the realm's board sprite binding.
    by_source = {"/assets/" + Path(e["source"]).relative_to("assets").as_posix(): e for e in entries}
    catalog["portraits"] = portrait_imports(catalog, by_source, entries, files)
    scopes.append("portraits")
    font_lock = json.loads((FONTS / "sha256.json").read_text())
    font_entries = []
    for relative, expected_hash in font_lock.items():
        source = FONTS / relative
        data = source.read_bytes()
        if digest(data) != expected_hash:
            raise RuntimeError(f"Pinned font/license changed: {relative}")
        destination = GENERATED / "FontSources" / relative
        files[destination] = data
        if source.suffix == ".ttf":
            if data[:4] != b"\x00\x01\x00\x00":
                raise RuntimeError(f"Expected static TrueType font: {relative}")
            count = struct.unpack(">H", data[4:6])[0]
            tags = {data[12 + 16 * i:16 + 16 * i] for i in range(count)}
            if b"fvar" in tags:
                raise RuntimeError(f"Variable font requires an explicit static source: {relative}")
            font_entries.append({"name": source.stem, "sha256": expected_hash,
                "source": source.relative_to(ROOT).as_posix(),
                "asset": destination.relative_to(PROJECT).as_posix(),
                "guid": guid(destination), "resource": f"ZKube/Fonts/{source.stem}",
                "fontAssetGuid": guid(GENERATED / RESOURCE / "Fonts" / f"{source.stem}.asset")})
    files[GENERATED / "FontSources/provenance.json"] = (FONTS / "provenance.json").read_bytes()
    catalog.update(assets=entries, fonts=font_entries,
        atlases=[{"scope": scope, "asset": (GENERATED / RESOURCE / "Atlases" / f"{scope}.spriteatlas").relative_to(PROJECT).as_posix(),
                  "guid": guid(GENERATED / RESOURCE / "Atlases" / f"{scope}.spriteatlas"),
                  "maxTextureSize": 2048 if scope == "portraits" else 4096,
                  "singleTexture": scope == "portraits"} for scope in scopes],
        importPolicy={"schema": 1, "source": "assets", "pixelsPerUnit": 100,
                      "filter": "Bilinear", "mipmaps": False, "readable": False,
                      "androidTextureFormat": "ASTC_6x6", "atlasMaxSize": 4096,
                      "atlasPadding": 4, "allowRotation": False, "tightPacking": False,
                      "includeAtlasInBuild": False,
                      "loading": "Explicit Resources.LoadAsync<SpriteAtlas> per realm; GetSprite by catalog name. Release old realm references before unloading. Audio is separate and music streams locally."})
    # Resolve every live function's asset path against copied bytes; fail missing files.
    for theme in catalog["themes"]:
        theme["sprites"] = [{"name": key, "atlas": by_source[value]["atlas"], "sprite": by_source[value]["sprite"]}
                            for key, value in theme["images"].items()]
        theme["audio"] = [{"context": key, "resource": by_source[value]["resource"]}
                          for key, value in theme["music"].items()]
    catalog["effectResources"] = [{"name": key, "resource": by_source[value]["resource"]}
                                  for key, value in catalog["effects"].items()]
    catalog_path = GENERATED / RESOURCE / "Catalog.json"
    files[catalog_path] = encoded(catalog)
    return files, catalog


def portrait_imports(catalog, by_source, entries, files):
    portraits = []
    for theme in catalog["themes"]:
        realm = theme["realmId"]
        source = by_source.get(theme["guardianPortrait"])
        if source is None or source["kind"] != "sprite" or source["scope"] != theme["id"]:
            raise RuntimeError(f"Guardian portrait must use its canonical existing theme sprite: {realm}")
        name = f"guardian-{realm}"
        destination = GENERATED / "Sprites" / "portraits" / f"{name}.png"
        if destination in files:
            raise RuntimeError(f"Duplicate portrait realm: {realm}")
        # Exact original PNG bytes and provenance; the existing Unity importer
        # performs the deterministic small sprite import, without authored art.
        data = files[PROJECT / source["asset"]]
        entry = dict(source, scope="portraits", name=name, sprite=name,
                     atlas="ZKube/Atlases/portraits", asset=destination.relative_to(PROJECT).as_posix(),
                     guid=guid(destination), maxTextureSize=256)
        entries.append(entry); files[destination] = data
        portraits.append({"realmId": realm, "source": source["source"], "sha256": source["sha256"],
                          "atlas": entry["atlas"], "sprite": name})
    return portraits


def metadata(path, folder=False):
    return (f"fileFormatVersion: 2\nguid: {guid(path)}\n" +
            ("folderAsset: yes\nDefaultImporter:\n  externalObjects: {}\n  userData: generated by unity/tools/import_assets.py\n" if folder else "")).encode()


def verify_meta(path):
    meta = Path(str(path) + ".meta")
    if not meta.is_file() or f"guid: {guid(path)}\n" not in meta.read_text():
        raise RuntimeError(f"Missing or changed generated GUID: {meta}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    # Flags are used rather than a positional action so commands read naturally.
    flags = parser.add_mutually_exclusive_group()
    flags.add_argument("--plan", action="store_true", dest="plan_only")
    flags.add_argument("--sync", action="store_true")
    flags.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files, catalog = plan()
    folders = set()
    for path in files:
        for parent in path.parents:
            if parent == ART: break
            folders.add(parent)
    # The Editor creates atlas/font assets with GUIDs carried by the catalog.
    # Avoid orphan .meta files: Unity removes metadata whose asset is absent.
    generated_editor_paths = [PROJECT / atlas["asset"] for atlas in catalog["atlases"]]
    generated_editor_paths += [GENERATED / "Resources" / (f["resource"] + ".asset") for f in catalog["fonts"]]
    for path in generated_editor_paths:
        for parent in path.parents:
            if parent == ART: break
            folders.add(parent)
    total = sum(e["bytes"] for e in catalog["assets"])
    if args.plan_only or not (args.sync or args.check):
        print(json.dumps({"sourceAssets": len(catalog["assets"]), "sourceBytes": total,
                          "fonts": len(catalog["fonts"]), "realms": len(catalog["themes"]),
                          "catalogSha256": digest(files[GENERATED / RESOURCE / "Catalog.json"])}, indent=2))
        return
    with editor_lease():
        for path in sorted(folders):
            if args.check:
                verify_meta(path)
            else:
                path.mkdir(parents=True, exist_ok=True)
                meta = Path(str(path) + ".meta")
                if not meta.exists(): meta.write_bytes(metadata(path, folder=True))
                verify_meta(path)
        for path, content in files.items():
            if args.check:
                if not path.is_file() or digest(path.read_bytes()) != digest(content):
                    raise SystemExit(f"Generated asset drift: {path.relative_to(ROOT)}; run --sync")
                verify_meta(path)
            else:
                if not path.exists() or path.read_bytes() != content: path.write_bytes(content)
                meta = Path(str(path) + ".meta")
                if not meta.exists(): meta.write_bytes(metadata(path))
                verify_meta(path)
        for path in generated_editor_paths:
            meta = Path(str(path) + ".meta")
            if path.exists(): verify_meta(path)
        expected = set(files) | set(generated_editor_paths)
        extras = [p.relative_to(GENERATED).as_posix() for p in GENERATED.rglob("*")
                  if p.is_file() and p.suffix != ".meta" and p not in expected]
        if extras:
            raise SystemExit("Unexpected generated files; review and remove only retired imports: " + ", ".join(extras))
    print(f"{'Checked' if args.check else 'Synchronized'} {len(catalog['assets'])} source assets, {len(catalog['fonts'])} pinned fonts, live palettes and stable GUIDs ({total} source bytes).")


if __name__ == "__main__":
    from cli import run_main
    run_main(main)
