// Generated by client/tools/unity/share-fixtures.ts from Intl.formatToParts; do not edit.
using System;
using System.Collections.Generic;
namespace ZKube.Local.App
{
    internal static class ShareNumberFormats
    {
        internal sealed class Policy
        {
            internal readonly string Separator;
            internal readonly int[] GroupSizes;
            internal readonly ulong MinimumGroupedValue;
            internal Policy(string separator, int[] sizes, ulong minimum)
            { Separator = separator; GroupSizes = sizes; MinimumGroupedValue = minimum; }
        }
        private static readonly Dictionary<string, Policy> Policies = new Dictionary<string, Policy>(StringComparer.OrdinalIgnoreCase)
        {
            { "fr", new Policy(" ", new[] { 3 }, 1000UL) },
            { "fr-FR", new Policy(" ", new[] { 3 }, 1000UL) },
            { "fr-CA", new Policy(" ", new[] { 3 }, 1000UL) },
            { "fr-BE", new Policy(" ", new[] { 3 }, 1000UL) },
            { "fr-CH", new Policy("'", new[] { 3 }, 1000UL) },
            { "fr-LU", new Policy(".", new[] { 3 }, 1000UL) },
            { "fr-MC", new Policy(" ", new[] { 3 }, 1000UL) },
            { "en-US", new Policy(",", new[] { 3 }, 1000UL) },
            { "en-CA", new Policy(",", new[] { 3 }, 1000UL) },
            { "de-DE", new Policy(".", new[] { 3 }, 1000UL) },
            { "de-CH", new Policy("'", new[] { 3 }, 1000UL) },
            { "nl-BE", new Policy(".", new[] { 3 }, 1000UL) },
            { "it-IT", new Policy(".", new[] { 3 }, 10000UL) },
            { "es-ES", new Policy(".", new[] { 3 }, 10000UL) },
            { "pt-PT", new Policy(" ", new[] { 3 }, 10000UL) },
            { "ru-RU", new Policy(" ", new[] { 3 }, 1000UL) },
            { "sv-SE", new Policy(" ", new[] { 3 }, 1000UL) },
            { "pl-PL", new Policy(" ", new[] { 3 }, 10000UL) },
            { "hi-IN", new Policy(",", new[] { 3, 2 }, 1000UL) },
        };
        internal static bool TryGet(string locale, out Policy policy) => Policies.TryGetValue(locale, out policy);
    }
}
