#!/usr/bin/env python3
"""Generate conditional presentation evidence from native trajectories/codecs."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[6]
SOURCE = ROOT / "fixtures/native-run-trajectories.json"
SCHEMA = ROOT / "unity/Assets/ZKube/Generated/NativeSchema.g.cs"


def generate():
    codecs = {}
    for match in re.finditer(r"public sealed class (\w+Request)\s*\{(.*?)(?=\n    public sealed class|\n\})", SCHEMA.read_text(), re.S):
        body = match[2]
        operation = re.search(r"public const uint Operation = (\d+);", body)
        if not operation:
            continue
        codecs[int(operation[1])] = {}
        for name, offset, length in re.findall(r"NativeWire\.Copy\((\w+), bytes, (\d+), (\d+)\)", body):
            codecs[int(operation[1])][name] = (int(offset), int(length), "bytes")
        for offset, length, name in re.findall(r"NativeWire\.Write\(bytes, (\d+), (\d+), (\w+)\)", body):
            codecs[int(operation[1])][name] = (int(offset), int(length), "int")
    cases = []
    for case in json.loads(SOURCE.read_text())["cases"]:
        authored = re.fullmatch(r"realm-(\d+)-(campaign|daily)", case["name"])
        if not authored and case["name"] not in {"Totem-perfect-clear-continuation", "Hammer-perfect-clear-continuation", "Wave-perfect-clear-continuation", "move-perfect-clear-grant", "move-perfect-clear-cap", "Hammer-perfect-clear-cap", "score-latch", "shape-latch", "blow-latch", "all-star-completion", "blocked-eleventh-row", "move-budget-exhaustion", "display-boundary-daily", "display-long-campaign-constraint", "balam-combo-2", "balam-earned-totem", "daily-pressure-crossing"}:
            continue
        item = {k: case[k] for k in ("name", "origin", "configHex", "initialStateHex", "finalStateHex")}
        # Synthetic rule/field probes retain the accepted Balam visual composition.
        # That is an explicit presentation choice, not a guardian-rule inference
        # or a claim that their synthetic config is an authored Balam run.
        item["realmId"] = int(authored[1]) if authored else 8
        item["realmOrigin"] = "native realm fixture" if authored else "explicit Balam presentation for synthetic native probe"
        item["configRequestHex"] = next(s["requestHex"] for s in case["steps"] if s["operation"] == 1)
        item["steps"] = []
        for step in case["steps"]:
            op = step["operation"]
            if op not in range(4, 9):
                continue
            raw = bytes.fromhex(step["requestHex"])
            fields = {}
            for name, (offset, length, kind) in codecs[op].items():
                value = raw[offset:offset + length]
                fields[name[0].lower() + name[1:]] = value.hex() if kind == "bytes" else int.from_bytes(value, "little")
            if fields["trace"] != 1:
                continue
            item["steps"].append({"operation": op, **{k: v for k, v in fields.items() if k not in {"config", "state", "trace"}}})
        cases.append(item)
    payload = json.dumps({"cases": cases}, separators=(",", ":"))
    return "// Generated by generate_evidence.py from native fixtures and generated codecs.\n#if UNITY_EDITOR || ZKUBE_EVIDENCE\nnamespace ZKube.Presentation.Evidence\n{\n    public static class BoardEvidenceData\n    {\n        public const string SourceSha256 = \"" + hashlib.sha256(SOURCE.read_bytes()).hexdigest() + "\";\n        public const string Json = @\"" + payload.replace('"', '""') + "\";\n    }\n}\n#endif\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = Path(__file__).with_name("BoardEvidenceData.g.cs")
    output = generate()
    if args.check:
        if not path.is_file() or path.read_text() != output:
            raise SystemExit("Presentation evidence data drift; run generate_evidence.py")
        print("Presentation evidence matches native fixtures and generated codecs")
    else:
        path.write_text(output)


if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(ROOT / "unity/tools"))
    from cli import run_main
    run_main(main, Path(__file__).with_name("BoardEvidenceData.g.cs"))
